# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift


use_frameworks!

target 'Demo' do

end

target 'DemoTests' do

pod 'RxSwift'
pod 'NSObject+Rx', :path => '../'

pod 'Quick'
pod 'Nimble'

end

