# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift


use_frameworks!

target 'Demo' do

end

target 'DemoTests' do

pod 'RxSwift', '~> 3.0.0'
pod 'NSObject+Rx', :path => '../'

pod 'Quick'
pod 'Nimble', '6.1.0'

end

